### ISSUE TITLE
part4.b: On where to put `express-async-errors`: `/app.js` or `/controllers/*.js` ?

### ISSUE THREAD

**Issue by janreggie** [fullstack-hy2020/fullstack-hy2020.github.io#1453]
In [4.b: Testing the backend § Eliminating the try-catch](https://fullstackopen.com/en/part4/testing_the_backend), `express-async-errors` is included in `/app.js`. However, by doing so,  running a `POST` request that will fail Mongoose validation causes the following to appear in my terminal:

```none
$ npm run dev
# ...
[ 'Method:', 'POST' ]
[ 'Path:  ', '/api/users' ]
[
  'Body:  ',
  { username: 'root', name: 'Superuser', password: 'salainen' }
]
[ '---' ]
/home/janreggie/dev/notes-backend/node_modules/mongoose/lib/document.js:2760
    this.$__.validationError = new ValidationError(this);
                               ^

ValidationError: User validation failed: username: Error, expected `username` to be unique. Value: `root`
    at model.Document.invalidate (/home/janreggie/dev/notes-backend/node_modules/mongoose/lib/document.js:2760:32)
    at /home/janreggie/dev/notes-backend/node_modules/mongoose/lib/document.js:2552:17
    at /home/janreggie/dev/notes-backend/node_modules/mongoose/lib/schematype.js:1273:9
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  errors: {
    username: ValidatorError: Error, expected `username` to be unique. Value: `root`
        at validate (/home/janreggie/dev/notes-backend/node_modules/mongoose/lib/schematype.js:1270:13)
        at /home/janreggie/dev/notes-backend/node_modules/mongoose/lib/schematype.js:1245:24
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      properties: {
        message: 'Error, expected `username` to be unique. Value: `root`',
        type: 'unique',
        validator: [Function (anonymous)],
        path: 'username',
        value: 'root'
      },
      kind: 'unique',
      path: 'username',
      value: 'root',
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'User validation failed'
}
[nodemon] app crashed - waiting for file changes before starting...
```

Putting the `import 'express-async-errors'` directive in _either_ `/controllers/notes.js` or `/controllers/users.js` seems to fix this issue. That is to say, if `/controllers/notes.js` contains the directive, and an invalid request happens to be fed to `/api/users`, it will be caught.

Looking at [the npm page for `express-async-errors`](https://www.npmjs.com/package/express-async-errors), it appears that the package _should_ be imported in the `controllers/XXX.js` files.

Note that I said `import 'express-async-errors'` since I'm trying out the es6 modules system. I don't know if using `require('express-async-errors')` makes this issue go away.

<details>
<summary>My `/app.js`</summary>

```js
import express from 'express'
import cors from 'cors'
import middleware from './utils/middleware.js'
import notesRouter from './controllers/notes.js'
import usersRouter from './controllers/users.js'
import 'express-async-errors'

const app = express()
app.use(cors())
app.use(express.static('build'))
app.use(express.json())
app.use(middleware.requestLogger)

app.use('/api/notes', notesRouter)
app.use('/api/users', usersRouter)

app.use(middleware.unknownEndpoint)
app.use(middleware.errorHandler)

export default app
```

</details>

<details>
<summary>My `/controllers/notes.js`</summary>

```js
import express from 'express'
import Note from '../models/note.js'

const notesRouter = express.Router()

notesRouter.get('/',
  async (_request, response) => {

    const notes = await Note.find({})
    response.json(notes)
  })

notesRouter.get('/:id',
  async (request, response) => {

    const note = await Note.findById(request.params.id)
    if (note) {
      response.json(note)
    } else {
      response.status(404).end()
    }
  })

notesRouter.post('/',
  async (request, response) => {

    const body = request.body
    const note = new Note({
      content: body.content,
      important: body.important || false,
      date: new Date()
    })

    const savedNote = await note.save()
    response.json(savedNote)
  })

notesRouter.delete('/:id',
  async (request, response) => {

    await Note.findByIdAndRemove(request.params.id)
    response.status(204).end()
  })

notesRouter.put('/:id',
  async (request, response) => {

    const body = request.body
    const note = {
      content: body.content,
      important: body.important
    }

    const updatedNote = await Note.findByIdAndUpdate(request.params.id, note, { new: true })
    response.json(updatedNote)
  })

export default notesRouter
```

</details>

<details>
<summary>My `/controllers/users.js`</summary>

```js
import bcrypt from 'bcrypt'
import express from 'express'
import User from '../models/user.js'

const usersRouter = express.Router()

usersRouter.get('/', async (_request, response) => {
  const users = await User.find({})
  response.json(users)
})


usersRouter.post('/', async (request, response) => {
  const body = request.body
  if (body.password === undefined) {
    return response.status(400).json({ error: '`password` must be provided'})
  }

  const saltRounds = 10
  const passwordHash = await bcrypt.hash(body.password, saltRounds)
  
  const user = new User({
    username: body.username,
    name: body.name,
    passwordHash
  })

  const savedUser = await user.save()
  response.json(savedUser)
})

export default usersRouter
```

</details>

**Comment by Kaltsoon** [comment]
From https://www.npmjs.com/package/express-async-errors: "Then require this script somewhere before you start using it". So your app.js should be:

```js
import express from 'express'
import 'express-async-errors' 

import cors from 'cors'
import middleware from './utils/middleware.js'
import notesRouter from './controllers/notes.js'
import usersRouter from './controllers/users.js'
```

**Comment by janreggie** [comment]
Oh, I see. Thank you so much.
I should've RTFM'd on that one.
