### ISSUE TITLE
Part10 - c GraphQL and Apollo client

### ISSUE THREAD

**Issue by hlf2016** [fullstack-hy2020/fullstack-hy2020.github.io#3055]
My app source code was [here](https://github.com/hlf2016/rate-repo-app.git)

The app  crashed frequently  after I ran 
```
npm install @apollo/client graphql
npm install @expo/metro-config

```

I got the warning 

```
 Validation Warning:

  Unknown option "watcher" with value {"additionalExts": ["env.local", "env"]} was found.
  This is probably a typing mistake. Fixing it will remove this message.
```

Besides the error 
```
Android Bundling failed 1730ms
error: Error: Cannot find module 'metro/src/lib/CountingSet'
Require stack:
- /Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/metro-config/build/serializer/environmentVariableSerializerPlugin.js
- /Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/metro-config/build/serializer/withExpoSerializers.js
- /Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/metro-config/build/ExpoMetroConfig.js
- /Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/cli/build/src/start/server/metro/resolveFromProject.js
- /Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/cli/build/src/start/server/metro/instantiateMetro.js
- /Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/cli/build/src/start/server/metro/MetroBundlerDevServer.js
- /Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/cli/build/src/start/server/DevServerManager.js
- /Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/cli/build/src/start/startAsync.js
- /Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/cli/build/src/start/index.js
- /Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/cli/build/bin/cli
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at _CountingSet (/Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/metro-config/build/serializer/environmentVariableSerializerPlugin.js:10:39)
    at getEnvPrelude (/Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/metro-config/build/serializer/environmentVariableSerializerPlugin.js:112:31)
    at environmentVariableSerializerPlugin (/Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/metro-config/build/serializer/environmentVariableSerializerPlugin.js:86:5)
    at /Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/@expo/metro-config/build/serializer/withExpoSerializers.js:137:17
    at build (/Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/metro/src/Server.js:675:28)
    at async Server.requestProcessor [as _processBundleRequest] (/Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/metro/src/Server.js:584:18)
    at async Server._processRequest (/Users/huanglongfei/fullstackopen/rate-repo-app/node_modules/metro/src/Server.js:430:9)
 ERROR  Your app just crashed. See the error below.
java.lang.RuntimeException: Attempting to call JS function on a bad application bundle: HMRClient.setup()
  com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
  android.os.Handler.handleCallback(Handler.java:790)
  android.os.Handler.dispatchMessage(Handler.java:99)
  com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
  android.os.Looper.loop(Looper.java:192)
  com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
  java.lang.Thread.run(Thread.java:764)

```

So what happened  .It has confused me for two days

**Comment by ElvannAbendroth** [comment]
There are compatibility issues with the Expo version 46, I've seen some of those error messages while trying to debug.  Try updating package.json to this:

```
{
  "name": "rate-repository-app",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "lint": "eslint ./src/**/*.{js,jsx} App.js --no-error-on-unmatched-pattern"
  },
  "dependencies": {
    "@expo/webpack-config": "^19.0.0",
    "expo": "~50.0.2",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.73.2",
    "react-native-web": "~0.19.6"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/eslint-parser": "^7.23.3",
    "eslint": "^8.56.0",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-native": "^4.1.0"
  },
  "private": true
}

```

**Comment by mluukkai** [comment]
part 10 has been updated so perhaps it also solved this
